name: effects_sdk
description: Video Effects SDK Flutter plugin for Web
version: 1.0.1
homepage: https://effectssdk.com/
repository: https://github.com/EffectsSDK/flutter-plugin

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_webrtc: '>=0.9.22 <=0.9.45'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      web:
        pluginClass: EffectsSDKWeb
        fileName: src/effects_sdk_web.dart
